apiVersion: apps/v1
kind: Deployment
metadata:
  name: contoso-microservice
spec:
  replicas: 0                   # Here we are telling K8S the number of containers to process the Redis list items
  selector:                     # Define the wrapping strategy
    matchLabels:                # Match all pods with the defined labels
      app: contoso-microservice # Labels follow the `name: value` template
  template:                     # This is the template of the pod inside the Deployment
    metadata:
      labels:
        app: contoso-microservice
    spec:
      containers:
        - image: mcr.microsoft.com/mslearn/samples/redis-client:latest
          name: contoso-microservice
          resources:
            requests:
              cpu: "1"
              memory: 128Mi
            limits:
              cpu: "1"
              memory: 128Mi
          env:
            - name: REDIS_HOST
              value: "redis-ask-demo.redis.cache.windows.net" # *** REPLACE with your value ***
            - name: REDIS_PORT
              value: "6379"                                        # *** REPLACE with your value ***
            - name: REDIS_LIST
              value: "keda"                                        # *** REPLACE with your value ***
            - name: REDIS_KEY
              value: "dApEDIkN8x9BILSpPfPKifQCnCfvDYIJfAzCaKg8Rns="  # *** REPLACE with your value ***