apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: scaled-contoso
spec:
  scaleTargetRef:
    apiVersion: apps/v1                             # Optional. Default: apps/v1
    kind: deployment                                # Optional. Default: Deployment
    name: contoso-microservice                      # Mandatory. Must be in the same namespace as the ScaledObject
    envSourceContainerName: contoso-microservice    # Optional. Default: .spec.template.spec.containers[0]
  pollingInterval: 30                               # Optional. Default: 30 seconds
  cooldownPeriod:  120                              # Optional. Default: 300 seconds
  minReplicaCount: 0                                # Optional. Default: 0
  maxReplicaCount: 20                               # Optional. Default: 100
  advanced:                                         # Optional. Section to specify advanced options
    restoreToOriginalReplicaCount: false            # Optional. Default: false
    horizontalPodAutoscalerConfig:                  # Optional. Section to specify HPA related options
      behavior:                                     # Optional. Use to modify HPA's scaling behavior
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15
  triggers:
  - type: redis
    metadata:
      # address:                  # Format must be host:port
      passwordFromEnv: REDIS_KEY
      listName: keda              # Required
      listLength: "2"            # Required
      enableTLS: "false"          # optional
      databaseIndex: "0"          # optional
      hostFromEnv: REDIS_HOST
      portFromEnv: REDIS_PORT